# NOTE: Explaination: https://pytezos.baking-bad.org/tutorials/02.html#operation-group
validation_passes = {
    'failing_noop': -1,
    'endorsement': 0,
    'endorsement_with_slot': 0,
    'proposals': 1,
    'ballot': 1,
    'seed_nonce_revelation': 2,
    'double_endorsement_evidence': 2,
    'double_baking_evidence': 2,
    'activate_account': 2,
    'reveal': 3,
    'transaction': 3,
    'origination': 3,
    'delegation': 3,
    'register_global_constant': 3,
}
operation_tags = {
    'endorsement': 0,
    'endorsement_with_slot': 10,
    'proposals': 5,
    'ballot': 6,
    'seed_nonce_revelation': 1,
    'double_endorsement_evidence': 2,
    'double_baking_evidence': 3,
    'activate_account': 4,
    'failing_noop': 17,
    'reveal': 107,
    'transaction': 108,
    'origination': 109,
    'delegation': 110,
    'register_global_constant': 111,
    'set_deposits_limit': 112,
    'tx_rollup_origination': 150,
    'tx_rollup_submit_batch': 151,
    'tx_rollup_commit': 152,
    'tx_rollup_return_bond': 153,
    'tx_rollup_finalize_commitment': 154,
    'tx_rollup_remove_commitment': 155,
    'tx_rollup_rejection': 156,
    'tx_rollup_dispatch_tickets': 157,
    'transfer_ticket': 158,
    'sc_rollup_originate': 200,
    'sc_rollup_add_messages': 201,
    'sc_rollup_cement': 202,
    'sc_rollup_publish': 203,
}
# FIXME: No backward compatibility
operation_tags = {
    **operation_tags,
    'double_preendorsement_evidence': 7,
    'preendorsement': 20,
    'endorsement': 21,
}