from pytezos.michelson.instructions.adt import *
from pytezos.michelson.instructions.arithmetic import *
from pytezos.michelson.instructions.boolean import *
from pytezos.michelson.instructions.compare import *
from pytezos.michelson.instructions.control import *
from pytezos.michelson.instructions.crypto import *
from pytezos.michelson.instructions.generic import *
from pytezos.michelson.instructions.jupyter import *
from pytezos.michelson.instructions.stack import *
from pytezos.michelson.instructions.struct import *
from pytezos.michelson.instructions.tezos import *
from pytezos.michelson.instructions.ticket import *
from pytezos.michelson.instructions.tzt import *
